:repository-owner: arduino-libraries
:repository-name: Arduino_HTS221

= {repository-name} Library for Arduino =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

Allows you to read the temperature and humidity sensors of your Nano 33 BLE Sense.

== The HTS221: very short introduction ==

The HTS221 is a temperature and humidity sensor designed and manufactured by ST Microelectronics, and currently facing end-of-life.

Its main use has been within air conditioning plants and domestic appliances, where it can provide alarm and/or control functions.

The data sheet can be downloaded https://www.st.com/resource/en/datasheet/hts221.pdf[here] (link checked on 11. 06. 2023).

The distinctive feature of HTS221, compared to other temperature and humidity sensors, is its programmability. Besides user configuration od things like data acquisition modes and rate, and unlike most thermo-hygrometric chips on the market, the HTS221 also allows user change of calibration parameters. This may detract somewhat from ease of use, but in exchange allows engineers and users to improve the sensor response in terms of accuracy (anyway, all chips present on the market are factory-calibrated by ST Microelectronics).

== User calibration ==

Calibration parameters can be changed by users using appropriate calls to the Wire.h library (no support is given to date in this library).

User calibration data are stored into HTS221 volatile memory, and are reloaded from the chip's flash memory whenever a "chip reboot" event occurs, or after a power-up.

It is recommended to all users wishing to change the chip's calibration parameters to provide their off-chip storage (e.g. on flash or EEPROM), and to write the stored parameters to HTS221 after any reboot/power-up.

== License ==

Copyright (c) 2019 Arduino SA. All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
